=== nltk/nltk/nltk_data/corpora/propbank/frames/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>

<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>

<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*
  
  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
  
<!ELEMENT roleset (note*, roles, ( example | note )*)>
<!ATTLIST roleset 
  id   ID #REQUIRED
  name CDATA #IMPLIED
  vncls CDATA #IMPLIED
  framnet CDATA #IMPLIED>
<!ELEMENT roles   (note | role)*>

<!ELEMENT role (vnrole*) >
<!-- 
  roles have a number (or actually a number or an "M" or an "A" associated
  with them.  The "M" stands for modifier and the "A" stands for agent. 
  The "A" is the agent only in the case where arg 0 is not agentive 
  (eg verbs that can take causative constructions). This number is encoded in
  the attribute 'n'

  'f' is an attribute which may contain function tags.  The current list of 
  available function tags are

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose - deprecated !!!
    PNC  purpose no cause
    CAU  cause
  
  additionally, function tags may be prepositions, indicating that the
  preposition in question can be associated with the argument/role
  presented.  For this reason, we can't restrict the values to an
  enumeration :(.

  The roles also have a 'vnr' attribute, which refers
  to verbnet v0.2 thematic roles.  Verbnet thematic roles are 

  Note That verbnet

-->
<!ATTLIST role 
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  descr CDATA #REQUIRED>

<!ELEMENT vnrole EMPTY>
<!ATTLIST vnrole
  vncls CDATA #REQUIRED

  vntheta (Actor1 | Actor2| Agent| Asset| Attribute| Beneficiary| Cause|
  Destination| Experiencer| Extent| Instrument| Location| Material| Patient|
  Patient1| Patient2| Predicate| Product| Recipient| Source| Stimulus| Theme|
  Theme1| Theme2| Time| Topic) #REQUIRED>
        


<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->
<!ELEMENT example (inflection?, note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  type CDATA #IMPLIED
  src  CDATA #IMPLIED>

<!ELEMENT text (#PCDATA)>

<!ELEMENT inflection EMPTY>
<!ATTLIST inflection
  person (third | other | ns) "ns"
  tense  (present | past | future | ns) "ns"
  aspect (perfect | progressive | both | ns) "ns"
  voice  (active | passive | ns) "ns"
  form   (infinitive | gerund | participle | full | ns) "ns">


<!-- the n and f attributes corresponds to those of the roles
     described above -->
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n CDATA #REQUIRED
  f CDATA #IMPLIED>

<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  f CDATA #IMPLIED>

=== nltk/nltk/data/corpora/propbank/frames/foam.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="foam">
<note>
  Frames file for 'foam' based on sentences in wsj.  Verbnet entry 43.4, 47.2.
</note>

<roleset id="foam.01" vncls="43.4 47.2" name="(cause to) become foamy">
<roles>
  <role n="0"  descr="causer of foaminess"/>
  <role n="1"  descr="foamy thing"/>
</roles>

<example name="agentive, no object">
<inflection person="ns" tense="ns" aspect="ns" voice="ns" form="gerund"/>
<text>
     But even though by some estimates it might cost the world as much
     as $100 billion between now and the year 2000 to convert to other
     coolants, foaming agents and solvents and to redesign equipment
     for these less efficient substitutes, the Montreal Protocol's
     legions of supporters say it is worth it. 
</text>
	<rel>foaming</rel>
	<arg n="0">agents</arg>
</example>

<example name="both args">
  <inflection person="ns" tense="past" aspect="ns" voice="active" form="full"/>
  <text>
     John foamed some milk for Mary's cappuccino.
  </text>
  <arg n="0"        >John</arg>
  <rel              >foamed</rel>
  <arg n="1"        >some milk for Mary's cappuccino</arg>
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/release.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="release">
<note>
  Frames file for 'release' based on survey of initial sentences of
  big corpus and comparison with 'let go'.  Except there is no 'let
  go'.
</note>

<roleset id="release.01" name="let go">
<roles>
  <role descr="releaser" n="0"/>
  <role descr="thing released" n="1"/>
  <role descr="released from" n="2"/>
</roles>

<example name="active">
  <text>
  NEC released a statement saying &quot;We feel sorry for having caused
  trouble to society.&quot;
  </text>
  <arg n="0">NEC</arg>
  <rel>released</rel>
  <arg n="1">a statement saying &quot;We feel sorry for having caused
  trouble to society.&quot;</arg>
</example>

<example name="passive">
  <text>
  A 50-state study released *trace* in September by Friends for
  Education, an Albuquerque NM school-research group....
  </text>
  <arg n="1">*trace*=A 50-state study</arg>
  <rel>released</rel>
  <arg f="TMP" n="m">in September</arg>
  <arg f="by" n="0">Friends for
  Education, an Albuquerque NM school-research group</arg>
</example>

<example name="with source">
  <text>
  Others just released *trace* from the majors...
  </text>
  <arg n="1">*trace*=Others</arg>
  <arg f="TMP" n="m">just</arg>
  <rel>released</rel>
  <arg f="from" n="2">the majors</arg>
</example>

<note>
Note that a record release is a distinctly different sense, but it
takes pretty much the same syntax.
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/clutter.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="clutter">
<note>
  Frames file for 'clutter' based on sentences in wsj.  Verbnet entry 9.8.
</note>

<roleset id="clutter.01" name="fill with random junk" vncls="9.8">
<roles>
  <role descr="agent of cluttering" n="0"><vnrole vncls="9.8" vntheta="Agent"/></role>
  <role descr="container, space" n="1"><vnrole vncls="9.8" vntheta="Destination"/></role>
  <role descr="random junk" n="2"><vnrole vncls="9.8" vntheta="Theme"/></role>
</roles>

<example name="adjectival">
<inflection aspect="ns" form="participle" person="third" tense="present" voice="passive"/>
<text>
    ``Now the field is less cluttered,'' he added.
</text>
        <arg f="TMP" n="M">Now</arg>
        <arg n="1">the field</arg>
        <arg f="EXT" n="M">less</arg>
        <rel>cluttered</rel>
</example>


<example name="verbal, agentive">
<inflection aspect="ns" form="infinitive" person="ns" tense="ns" voice="active"/>
<text>
    After the confusion surrounding the change of the Coke formula in
    1985, Coca-Cola was reluctant [*-1] to clutter the Classic name
    with a brand extension. 
</text>
        <arg n="0">[*-1] -&gt;  Coca-Cola</arg>
        <rel>clutter</rel>
        <arg n="1">the Classic name</arg>
        <arg f="with" n="2">a brand extension</arg>
</example>

<example name="unaccusative">
  <inflection aspect="ns" form="full" person="third" tense="present" voice="active"/>
  <text>
     Cast-off clothing, half-read books, pizza crusts, and the
     occasional weapon of mass destruction clutter John's room.
  </text>
  <arg n="2">Cast-off clothing, half-read books, pizza crusts, and the
     occasional weapon of mass destruction</arg>
  <rel>clutter</rel>
  <arg n="1">John's room</arg>
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/accent.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="accent">

<roleset id="accent.01" name="to bring out certain features">
<roles>
  <role descr="decorator" n="0"/>
  <role descr="thing decorated" n="1"/>
  <role descr="decorations" n="2"/>
</roles>


<example name="BNC example">
  <text>
It's natural that Yuri should so enjoy dressing down , when for some much of his life he has been zipped into elaborate Bolshoi costumes, his cheekbones and
eyes accented by thick, expertly applied theatrical make-up.
  </text>

  <rel>accented</rel>
  <arg n="1">his cheekbones and eyes</arg>
  <arg f="by" n="2">thick, expertly applied theatrical make-up</arg>
</example>

<example name="made up"> 
  <text>
They accented the new dining area with throw pillows of a ghastly turquoise hue.
  </text>
  <arg n="0">They</arg>
  <rel>accented</rel>
  <arg n="1">the new dining area</arg>
  <arg f="with" n="2">throw pillos of a ghastly turquoise hue</arg>
</example>

</roleset>
</predicate>
<note>
  frames created by Ruth
</note>

</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/forfeit.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="forfeit">
<note>
Frames file for 'forfeit' based on sentences in financial subcorpus
and automatic expansion via verbnet.
</note>

<roleset id="forfeit.01" name="give up (to)" vncls="13.2">
<roles>
	<role descr="giver" n="0">
		
  <vnrole vncls="13.2" vntheta="Agent"/></role>
 
	<role descr="thing given" n="1">
		
  <vnrole vncls="13.2" vntheta="Theme"/></role>
 
	<role descr="entity given to" n="2">
		
  <vnrole vncls="13.2" vntheta="Recipient"/></role>
 
</roles>

<example name="usually without benefactive">
<inflection aspect="ns" form="infinitive" person="ns" tense="ns" voice="ns"/>
<text>
    In addition, Mrs. Lidgerwood said, Norfolk is likely *trace* to
    draw down its cash initially to finance the purchases and thus
    forfeit some interest income. 
</text>
        <arg n="0">*trace* -&gt;  Norfolk</arg>
        <arg f="DIS" n="M">thus</arg>
        <rel>forfeit</rel>
        <arg n="1">some interest income</arg>
</example>

<example name="all args" src="surrender.01">
  <text>
    John forfeited his prize collection of bottle caps to Mary.
  </text>
  <arg n="0">John</arg>
  <rel>forfeited</rel>
  <arg n="1">his prize collection of bottle caps</arg>
  <arg f="to" n="2">Mary</arg>
</example>


</roleset>

</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/bang.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="bang">
<note>
  Frames file for 'bang' based on sentences in wsj.  Verbnet entries
  18.1, 43.2, 18.4, and 9.3; Framenet entry Motion noise.
</note>

<roleset id="bang.01" name="emit banging noise" vncls="43.2">
<roles>
  <role descr="thing emitting noise" n="0">
        <vnrole vncls="43.2" vntheta="Theme"/></role>
</roles>

<example name="bang!">
  <inflection aspect="ns" form="full" person="ns" tense="past" voice="active"/>
  <text>
     The window shutters banged in the wind.
  </text>
  <arg n="0">The window shutters</arg>
  <rel>banged</rel>
  <arg f="LOC" n="m">in the wind</arg>
</example>

<note>
</note>

</roleset>

<roleset id="bang.02" name="strike so as to make banging noise" vncls="18.1 18.4-1">
<roles>
  <role descr="striker, agent" n="0">
        <vnrole vncls="18.1" vntheta="Agent"/></role>
  <role descr="thing hit" n="1">
        <vnrole vncls="18.1" vntheta="Patient"/>
        <vnrole vncls="18.4-1" vntheta="Theme"/></role>
  <role descr="attribute of arg1" n="2"/>
</roles>

<example name="just transitive">
<inflection aspect="ns" form="full" person="third" tense="present" voice="active"/>
<text>
    He bangs on the piece of paper in frustration, then turns and
    walks away. 
</text>
        <arg n="0">He</arg>
        <rel>bangs</rel>
        <arg f="on" n="1">the piece of paper</arg>
        <arg f="MNR" n="M">in frustration</arg>
</example>

<example name="He's back!">
  <inflection aspect="ns" form="full" person="ns" tense="past" voice="active"/>
  <text>
    John banged open the lid of his coffin.
  </text>
  <arg n="0">John</arg>
  <rel>banged</rel>
  <arg n="2">open</arg>
  <arg n="1">the lid of his coffin</arg>
</example>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/quash.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="quash">
<note>
  Frames file for 'quash' based on sentences in financial subcorpus.
  Yes, it actually occurs more than once.  Variant of 'squash'.
  Verbnet entries carve-21.2-1 funnel-9.3 knead-26.5; other framed
  members include: push (variant), wind.
</note>

<roleset id="quash.01" name="squash">
<roles>
  <role descr="squasher" n="0"/>
  <role descr="thing squashed" n="1"/>
</roles>

<example name="no arg2">
<text>
    UAL Corp.'s board quashed any prospects for an immediate revival
    of a labor-management buy-out, saying United Airlines' parent
    should remain independent for now. 
</text>
        <arg n="0">UAL Corp. 's board</arg>
        <rel>quashed</rel>
        <arg n="1">any prospects for an immediate revival of a
        labor-management buy-out</arg> 
        <arg f="ADV" n="M">saying United Airlines' parent should
        remain independent for now</arg> 
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/data/corpora/propbank/frames/enter.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="enter">
<note>
  Frames file for 'enter' based on sentences in financial subcorpus.
  Verbnet class 51.1, other framed members are 'leave'.  Also
  comparison with 'go in'.
</note>

<roleset id="enter.01" name="enter, go in" vncls="51.1-1">
<roles>
  <role descr="entity entering" n="0">
		
  <vnrole vncls="51.1-1" vntheta="Theme"/></role>

  <role descr="place or thing entered" n="1">
		
  <vnrole vncls="51.1-1" vntheta="Location"/></role>

</roles>

<example name="place entered as NP">
<text>
    An ambitious expansion has left Magna with excess capacity and a
    heavy debt load as the automotive industry enters a downturn.
</text>
        <arg n="0">the automotive industry</arg>
        <rel>enters</rel>
        <arg n="1">a downturn</arg>
</example>

<example name="place entered as a PP">
<text>
    The two concerns said they entered into a definitive merger
    agreement under which Ratners will begin a tender offer for all of
    Weisfield's common shares for $57.50 each.
</text>
        <arg n="0">they</arg>
        <rel>entered</rel>
        <arg f="into" n="1">a definitive merger agreement under which
        Ratners will begin a tender offer for all of Weisfield's
        common shares for $57.50 each</arg>
</example>

</roleset>

<roleset id="enter.02" name="submit, cause to enter" vncls="29.2">
<roles>
  <role descr="submitter" n="0"><vnrole vncls="29.2" vntheta="Agent"/></role>
  <role descr="thing submitted" n="1"><vnrole vncls="29.2" vntheta="Theme"/></role>
  <role descr="submitted to" n="2"><vnrole vncls="29.2" vntheta="Predicate"/></role>
  <role descr="benefactive" n="3"/>
</roles>

<example name="submit, transitive">
<text>
    On Oct. 19, 1987, some investors learned the consequences of
    *trace* entering ``good-til-canceled limit orders'' and then
    forgetting about them. 
</text>
        <arg n="0">*trace* -&gt;  some investors</arg>
        <rel>entering</rel>
        <arg n="1">good-til-canceled limit orders</arg>
</example>

<example name="including manner">
<text>
    A limit order to sell could be entered *trace* at that price .
</text>
        <arg f="MOD" n="M">could</arg>
        <rel>entered</rel>
        <arg n="1">*trace* -&gt;  A limit order  to sell</arg>
        <arg f="MNR" n="M">at that price</arg>
</example>

<example name="with benefactive">
<text>
    And even when a specific order is acceptable to an exchange, a
    brokerage firm can refuse *trace* to enter it for a customer.
</text>
        <arg n="0">*trace* -&gt;  a brokerage firm</arg>
        <rel>enter</rel>
        <arg n="1">it</arg>
        <arg f="for" n="3">a customer</arg>
</example>

<example name="dunno why Arg2 didn't show up">
  <text>
    John entered his crayon drawings into an art competition.
  </text>
  <arg n="0">John</arg>
  <rel>entered</rel>
  <arg n="1">his crayon drawings</arg>
  <arg f="into" n="2">an art competition</arg>
</example>

</roleset>
</predicate>
</frameset>
