=== nltk/nltk/nltk_data/corpora/propbank/frames/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>

<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>

<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*
  
  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
  
<!ELEMENT roleset (note*, roles, ( example | note )*)>
<!ATTLIST roleset 
  id   ID #REQUIRED
  name CDATA #IMPLIED
  vncls CDATA #IMPLIED
  framnet CDATA #IMPLIED>
<!ELEMENT roles   (note | role)*>

<!ELEMENT role (vnrole*) >
<!-- 
  roles have a number (or actually a number or an "M" or an "A" associated
  with them.  The "M" stands for modifier and the "A" stands for agent. 
  The "A" is the agent only in the case where arg 0 is not agentive 
  (eg verbs that can take causative constructions). This number is encoded in
  the attribute 'n'

  'f' is an attribute which may contain function tags.  The current list of 
  available function tags are

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose - deprecated !!!
    PNC  purpose no cause
    CAU  cause
  
  additionally, function tags may be prepositions, indicating that the
  preposition in question can be associated with the argument/role
  presented.  For this reason, we can't restrict the values to an
  enumeration :(.

  The roles also have a 'vnr' attribute, which refers
  to verbnet v0.2 thematic roles.  Verbnet thematic roles are 

  Note That verbnet

-->
<!ATTLIST role 
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  descr CDATA #REQUIRED>

<!ELEMENT vnrole EMPTY>
<!ATTLIST vnrole
  vncls CDATA #REQUIRED

  vntheta (Actor1 | Actor2| Agent| Asset| Attribute| Beneficiary| Cause|
  Destination| Experiencer| Extent| Instrument| Location| Material| Patient|
  Patient1| Patient2| Predicate| Product| Recipient| Source| Stimulus| Theme|
  Theme1| Theme2| Time| Topic) #REQUIRED>
        


<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->
<!ELEMENT example (inflection?, note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  type CDATA #IMPLIED
  src  CDATA #IMPLIED>

<!ELEMENT text (#PCDATA)>

<!ELEMENT inflection EMPTY>
<!ATTLIST inflection
  person (third | other | ns) "ns"
  tense  (present | past | future | ns) "ns"
  aspect (perfect | progressive | both | ns) "ns"
  voice  (active | passive | ns) "ns"
  form   (infinitive | gerund | participle | full | ns) "ns">


<!-- the n and f attributes corresponds to those of the roles
     described above -->
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n CDATA #REQUIRED
  f CDATA #IMPLIED>

<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  f CDATA #IMPLIED>

=== nltk/nltk/data/corpora/propbank/frames/hound.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="hound">
<note>
  Frames file for 'hound' based on survey of sentences in the WSJ
  corpus. 
</note>

<roleset id="hound.01" name="to harass or nag" vncls="-">
<roles>
  <role descr="harasser" n="0"/>
  <role descr="entity hounded" n="1"/>
</roles>

<example name="transitive">
<inflection aspect="ns" form="full" person="ns" tense="past" voice="active"/>
<text>
 In testimony recorded [*] in the grand jury report , court employees said [0] the judge , now 59 years old , harassed his secretaries , made imperial demands on his staff and hounded anyone who [*T*-157] crossed him .
</text>
	<arg n="0">the judge , now 59 years old ,</arg>
	<rel>hounded</rel>
	<arg n="1">anyone who [*T*-157] crossed him</arg>
</example>


</roleset>
</predicate>


</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/confirm.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="confirm">
<note>
  Frames file for 'confirm' based on sentences in financial
  subcorpus.  No access to verbnet.  Comparison to 'deny'.
</note>

<roleset id="confirm.01" name="confirm, attest the truth of a proposition" vncls="29.2">
<roles>
  <role descr="confirmer" n="0">
		
  <vnrole vncls="29.2" vntheta="Agent"/></role>

  <role descr="thing confirmed, statement or proposition" n="1">
		
  <vnrole vncls="29.2" vntheta="Predicate"/></role>

  <role descr="benefactive, hearer" n="2">
		
  <vnrole vncls="29.2" vntheta="Theme"/></role>

</roles>

<example name="justifying the comparison">
<text>
    He declined *trace* to confirm or deny reports that Provigo
    executive Henri Roy is trying to put together a management buy-out
    of the catalogue showroom unit. 
</text>
        <arg n="0">*trace* -&gt;  He</arg>
        <rel>confirm</rel>
        <arg n="1">reports that Provigo executive Henri Roy is trying
        to put together a management buy-out of the catalogue showroom
        unit</arg> 
</example>

<example name="watch the complementizers">
<text>
    GM confirmed Friday that it received permission late Thursday from
    U.S. antitrust regulators to increase its Jaguar holdings past the
    $15 million level. 
</text>
        <arg n="0">GM</arg>
        <rel>confirmed</rel>
        <arg f="TMP" n="M">Friday</arg>
        <arg n="1">it received permission late Thursday from
        U.S. antitrust regulators to increase its Jaguar holdings past
        the $15 million level</arg> 
</example>

<example name="with hearer">
  <text>
    John confirmed to Mary that he'd been sleeping in a box under a
    bridge.
  </text>
  <arg n="0">John</arg>
  <rel>confirmed</rel>
  <arg f="to" n="2">Mary</arg>
  <arg n="1">he'd been sleeping in a box under a
    bridge.</arg>
</example>

<note>
I wonder if we'll get the religious sense of confirm?
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/beget.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="beget">
<note>
  Frames file for 'beget' based on sentences in wsj.  Verbnet entry
  27.
</note>

<roleset id="beget.01" name="bring into existence" vncls="27">
<roles>
  <role descr="begetter" n="0"><vnrole vncls="27" vntheta="Theme1"/></role>
  <role descr="begotten?" n="1"><vnrole vncls="27" vntheta="Theme2"/></role>
</roles>

<example name="I love strong verbs">
<inflection aspect="ns" form="full" person="ns" tense="past" voice="active"/>
<text>
    The concept begot a slew of copycats, but the banks stopped
    promoting the packages. 
</text>
        <arg n="0">The concept</arg>
        <rel>begot</rel>
        <arg n="1">a slew of copycats</arg>
</example>

<note>
Actually, I believe the past tense of 'beget' is 'begat.'  OED doesn't
agree with me, though, calling 'begat' archaic.  Pfah, what do they know?
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/data/corpora/propbank/frames/pounce.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="pounce">
<note>
  Frames file for 'pounce' based on survey of sentences in the WSJ
  corpus. 
</note>

<roleset id="pounce.01" name="to attack suddenly" vncls="-">
<roles>
  <role descr="attacker, agent" n="0"/>
  <role descr="thing pounced on" n="1"/>
</roles>

<example name="transitive">
<inflection aspect="ns" form="infinitive" person="ns" tense="ns" voice="active"/>
<text>
 Here was [*T*-1] the state security appartus poised [*] to pounce on any words or acts of provocation , let alone revolution .
</text>
	<arg n="0">[*] -&gt;  the state security appartus</arg>
	<rel>pounce</rel>
	<arg f="on" n="1">any words or acts of provocation , let alone revolution</arg>
</example>


</roleset>
</predicate>


</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/wade.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="wade">
<note>
  Frames file for 'wade' based on sentences in wsj.  Verbnet entry
  51.3.2, Framenet entry Self-motion.
</note>

<roleset id="wade.01" name="walk through water" vncls="51.3.2">
<roles>
  <role descr="wader" n="0"><vnrole vncls="51.3.2" vntheta="Theme"/></role>
  <role descr="water" n="1"><vnrole vncls="51.3.2" vntheta="Location"/></role>
</roles>

<example name="metaphorical?">
<inflection aspect="ns" form="infinitive" person="ns" tense="ns" voice="ns"/>
<text>
    Geoffrey Goodfellow, who dropped out of high school back in the
    1970s to manage a computer network at a California research firm,
    says: ``Old network hands have started to turn off the network
    because they don't have time [*] to wade through the muck.'' 
</text>
        <arg n="0">[*] -&gt;  they</arg>
        <rel>wade</rel>
        <arg f="through" n="1">the muck</arg>
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/copyright.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="copyright">
<note>
  Frames file for 'copyright' based on sentences in wsj.  No Verbnet entry.
</note>

<roleset id="copyright.01" vncls="-" name="acquire exclusive rights to printed material">
<roles>
  <role n="0"  descr="copyrighter"/>
  <role n="1"  descr="printed material"/>
</roles>

<example name="adjectival">
<inflection person="ns" tense="ns" aspect="ns" voice="passive" form="participle"/>
<text>
     That finding, the report says, casts doubt on the record
     industry's contention that the new generation of digital
     recording equipment will inevitably lead to wholesale abuse of
     copyrighted material by home tapers. 
</text>
	<rel>copyrighted</rel>
	<arg n="1">material</arg>
</example>

<example name="agentive">
  <inflection person="ns" tense="past" aspect="ns" voice="active" form="full"/>
  <text>
     John copyrighted his disseratation.
  </text>
  <arg n="0"        >John</arg>
  <rel              >copyrighted</rel>
  <arg n="1"        >his dissertation</arg>
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/data/corpora/propbank/frames/slam.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="slam">

<note>
Frames file for 'slam' based on sentences in financial subcorpus and
automatic generation from Verbnet classes.
</note>

<roleset id="slam.01" name="throw violently" vncls="17.1">
<roles>
<role descr="thrower" n="0">
		
  <vnrole vncls="17.1" vntheta="Agent"/></role>

<role descr="thing thrown" n="1">
		
  <vnrole vncls="17.1" vntheta="Patient"/></role>

<role descr="thrown at, to, over, etc" n="2">
		
  <vnrole vncls="17.1" vntheta="Destination"/></role>

</roles>

<example name="all args">
  <inflection aspect="ns" form="full" person="ns" tense="past" voice="active"/>
  <text>
    John slammed the book onto the table.
  </text>
  <arg n="0">John</arg>
  <arg n="1">slammed</arg>
  <rel>the book</rel>
  <arg f="onto" n="2">the table</arg>
</example>

</roleset>

<roleset id="slam.02" name="hit hard" vncls="18.4-1">
<roles>
<role descr="agent, hitter - animate only!" n="0"/>
<role descr="thing hit" n="1">
		
  <vnrole vncls="18.4-1" vntheta="Theme"/></role>

<role descr="instrument, thing hit by or with" n="2"><vnrole vncls="18.4-1" vntheta="Location"/></role>
</roles>

<example name="transitive">
<inflection aspect="ns" form="full" person="ns" tense="past" voice="active"/>
<text>
    Twice in two weeks the unraveling of the on-again, off-again UAL
    buy-out slammed the stock market. 
</text>
        <arg f="TMP" n="M">Twice</arg>
        <arg f="TMP" n="M">in two weeks</arg>
        <arg n="0">the unraveling of the on-again , off-again UAL buy-out</arg>
        <rel>slammed</rel>
        <arg n="1">the stock market</arg>
</example>

<example name="with instrument" src="hit.01">
  <text>
    The firm has also been slammed *trace* with big financial settlements.
  </text>
  <arg n="1">The firm</arg>
  <arg f="dis" n="m">also</arg>
  <rel>slammed</rel>
  <arg f="with" n="2">big financial settlements</arg>
</example>

</roleset>

</predicate>
</frameset>

=== nltk/nltk/data/corpora/propbank/frames/age.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="age">
<note>
  Frames file for 'age' based on survey of sentences in the WSJ
  corpus. 
</note>

<roleset id="age.01" name="to make or become old or older" vncls="45.4">
<roles>
  <role descr="causer of aging, agent" n="0"><vnrole vncls="45.4" vntheta="Agent"/></role>
  <role descr="entity getting old" n="1"><vnrole vncls="45.4" vntheta="Patient"/></role>
  <role descr="attribute (how old)" n="2"/>
</roles>



<example name="intransitive">
<inflection aspect="perfect" form="participle" person="third" tense="present" voice="active"/>
<text>
 `` Oil of Olay brought with it the baggage of [*] being used [*-1] basically by older women who [*T*-2] had already aged , '' says [*T*-3] David Williams , a consultant with New England Consulting Group .
</text>
	<arg n="1">[*T*-2] -&gt;  who -&gt;  older women</arg>
	<arg f="TMP" n="M">already</arg>
	<rel>aged</rel>
</example>


<example name="with Arg2">
<inflection aspect="ns" form="participle" person="ns" tense="ns" voice="ns"/>
<text>
 In 1980 , the study says [0] [*T*-1] , prosecutors surveyed [*] filed charges against 25 defendants for each 100,000 people aged 18 years and older .
</text>
	<arg n="1">each 100,000 people</arg>
	<rel>aged</rel>
	<arg n="2">18 years and older</arg>
</example>


</roleset>
</predicate>


</frameset>
