=== nltk/nltk/nltk_data/corpora/propbank/frames/frameset.dtd
<!--
                    dtd for predicate argument lexicon files

 Each file will contain a set of predicates associated with a particular
 lemma (including phrasal variants,  like 'keep_from', etc)

 Each predicate will contain a set of roles in an entity called a roleset.  The
 rolesets give mneumonics of the argument labels for each different set of
 arguments.  Multiple rolesets per predicate are necessary for the accomodation
 of different senses of the predicate.

 Each roleset associates the argument labels with a set of examples
 demonstrating some of the primary considerations in predicate argument
 annotation for the predicate+roleset in consideration.  The examples contain
 plain text sentences and then assign arguments to segments of the sentence.
 The examples usually have names which are often space delimited descriptions
 of the annotation.  The examples often have types which describe, in a
 nutshell, some primary linguistic properties such as "benefactive" or
 "agentive".  The type attribute may also include a phrasal particle variant
 (eg type="keep pace") so as to indicate the guidelines for annotation of these
 cases.

 The entire document can be decorated with notes for unstructured description of
 the information presented.
-->
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>

<!ELEMENT predicate (note | roleset)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>

<!--
  The roleset's levine class attribute takes the following form:

  -|\d+(\.\d+)*( \d+(\.\d+)*)*
  
  where '-' means there is no levine class
  and something like 47.2 means 47.2 is a levine class of this
  roleset.  The list of levine classes is space delimited
-->
  
<!ELEMENT roleset (note*, roles, ( example | note )*)>
<!ATTLIST roleset 
  id   ID #REQUIRED
  name CDATA #IMPLIED
  vncls CDATA #IMPLIED
  framnet CDATA #IMPLIED>
<!ELEMENT roles   (note | role)*>

<!ELEMENT role (vnrole*) >
<!-- 
  roles have a number (or actually a number or an "M" or an "A" associated
  with them.  The "M" stands for modifier and the "A" stands for agent. 
  The "A" is the agent only in the case where arg 0 is not agentive 
  (eg verbs that can take causative constructions). This number is encoded in
  the attribute 'n'

  'f' is an attribute which may contain function tags.  The current list of 
  available function tags are

    EXT  extent
    LOC  location
    DIR  direction
    NEG  negation  (not in PREDITOR)
    MOD  general modification
    ADV  adverbial modification
    MNR  manner
    PRD  secondary predication
    REC  recipricol (eg herself, etc)
    TMP  temporal
    PRP  purpose - deprecated !!!
    PNC  purpose no cause
    CAU  cause
  
  additionally, function tags may be prepositions, indicating that the
  preposition in question can be associated with the argument/role
  presented.  For this reason, we can't restrict the values to an
  enumeration :(.

  The roles also have a 'vnr' attribute, which refers
  to verbnet v0.2 thematic roles.  Verbnet thematic roles are 

  Note That verbnet

-->
<!ATTLIST role 
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  descr CDATA #REQUIRED>

<!ELEMENT vnrole EMPTY>
<!ATTLIST vnrole
  vncls CDATA #REQUIRED

  vntheta (Actor1 | Actor2| Agent| Asset| Attribute| Beneficiary| Cause|
  Destination| Experiencer| Extent| Instrument| Location| Material| Patient|
  Patient1| Patient2| Predicate| Product| Recipient| Source| Stimulus| Theme|
  Theme1| Theme2| Time| Topic) #REQUIRED>
        


<!--
  examples may contain inflectional information and notes notes
  After that, they contain the text of an example followed by
  the argument structure.

  The src attribute is for automatically retrieved examples
  and refers to a roleset identifier.
-->
<!ELEMENT example (inflection?, note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  type CDATA #IMPLIED
  src  CDATA #IMPLIED>

<!ELEMENT text (#PCDATA)>

<!ELEMENT inflection EMPTY>
<!ATTLIST inflection
  person (third | other | ns) "ns"
  tense  (present | past | future | ns) "ns"
  aspect (perfect | progressive | both | ns) "ns"
  voice  (active | passive | ns) "ns"
  form   (infinitive | gerund | participle | full | ns) "ns">


<!-- the n and f attributes corresponds to those of the roles
     described above -->
<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n CDATA #REQUIRED
  f CDATA #IMPLIED>

<!-- a rel can have an "f" attribute for a single reason, so that
     auxilliary uses of the verb "have" can be marked as such.
     There should be no other "f" attributes -->
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  f CDATA #IMPLIED>

=== nltk/nltk/nltk_data/corpora/propbank/frames/lie.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="lie">
<note>
  Frames file for 'lie' based on sentences in financial subcorpus.
  Verbnet classes assuming_position-50 spatial_configuration-47.6,
  which ignores one major sense.  Comparison to 'lay' and 'sit'
</note>

<roleset id="lie.01" name="assume a horizontal position, more generally 'exist'" vncls="47.6 50">
<roles>
  <role descr="entity in the position" n="1">
		
		
  <vnrole vncls="47.6" vntheta="Theme"/><vnrole vncls="50" vntheta="Agent"/></role>

  <role descr="location" n="2">
		
		
  <vnrole vncls="47.6" vntheta="Location"/><vnrole vncls="50" vntheta="Location"/></role>

</roles>

<example name="exist">
<text>
    But any chance for prices to surge above fair value lies in the
    speculation that accompanies a vigorous merger and buy-out
    business, and UAL has obviously put a damper on that. 
</text>
        <arg f="DIS" n="M">But</arg>
        <arg n="1">any chance for prices to surge above fair value</arg>
        <rel>lies</rel>
        <arg f="in" n="2">the speculation that accompanies a vigorous
        merger and buy-out business</arg> 
</example>

<example name="horizontal position">
  <text>
    John lies in bed until noon every day.
  </text>
  <arg n="1">John</arg>
  <rel>lies</rel>
  <arg f="in" n="2">bed</arg>
  <arg f="TMP" n="m">until noon</arg>
  <arg f="TMP" n="m">every day</arg>
</example>

<note>
</note>

</roleset>

<roleset id="lie.02" name="tell a falsehood" vncls="-">
<roles>
  <role descr="liar" n="0"/>
  <role descr="lie" n="1"/>
  <role descr="hearer" n="2"/>
</roles>

<example name="intransitivelly">
<text>
    He is also accused of *trace* lying under oath and of leaking
    information obtained from a wiretap he supervised.
</text>
        <arg n="0">*trace* -&gt; He</arg>
        <rel>lying</rel>
        <arg f="LOC" n="M">under oath</arg>
</example>

<example name="all args">
  <text>
    John lied to Mary about his whereabouts during their planned date.
  </text>
  <arg n="0">John</arg>
  <rel>lied</rel>
  <arg f="to" n="2">Mary</arg>
  <arg f="about" n="1">his whereabouts during their planned date</arg>
</example>

<note>
</note>

</roleset>
</predicate>

<predicate lemma="lie_down">

<roleset id="lie.03" name="more explicit horizontal position" vncls="50">
<roles>
  <role descr="entity lying down" n="1">
		
  <vnrole vncls="50" vntheta="Agent"/></role>

  <role descr="location" n="2">
		
  <vnrole vncls="50" vntheta="Location"/></role>

</roles>

<example name="no location">
<text>
    Wall Street's New Guard isn't likely *trace* to take all this
    *trace* lying down for long, however.
</text>
        <arg n="1">*trace* -&gt; *trace* -&gt; Wall Street's New Guard</arg>
        <rel>[ lying] [ down]</rel>
</example>

<example name="more clear">
  <text>
    John is going *trace* to lay down on the floor and cry.
  </text>
  <arg n="1">*trace* -&gt; John</arg>
  <rel>lay down</rel>
  <arg f="on" n="2">the floor</arg>
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/data/corpora/propbank/frames/legalize.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="legalize">
<note>
  Frames file for 'legalize' based on sentences in wsj.  No Verbnet entry.
</note>

<roleset id="legalize.01" name="make legal" vncls="-">
<roles>
  <role descr="legislative body, agent" n="0"/>
  <role descr="thing now legal" n="1"/>
</roles>

<example name="pretty simple, really">
<inflection aspect="ns" form="gerund" person="ns" tense="present" voice="active"/>
<text>
    In East Berlin, Communist Party officials considered *trace*
    legalizing New Forum, the country's largest opposition alliance,
    as about 20,000 demonstrators staged protests in three cities to
    press demands for democratic freedoms. 
</text>
        <arg n="0">*trace* -&gt;  Communist Party officials</arg>
        <rel>legalizing</rel>
        <arg n="1">New Forum, the country's largest opposition alliance</arg>
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/imperil.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="imperil">
<note>
  Frames file for 'imperil' based on sentences in financial subcorpus.
  No Verbnet entry, surprise surprise.  No comparison.
</note>

<roleset id="imperil.01" name="put into danger">
<roles>
  <role descr="causer of danger (agent or instrument)" n="0"/>
  <role descr="entity in danger" n="1"/>
</roles>

<example name="passive">
<text>
    It is possible then that Santa Fe's real estate -- even in a state
    imperiled *trace* by earthquakes -- could, one day, fetch a king's
    ransom. 
</text>
        <rel>imperiled</rel>
        <arg n="1">*trace* -&gt;  a state</arg>
        <arg f="by" n="0">earthquakes</arg>
</example>

<note>
If we see any examples with both agent and instrument, arg0 will have
to be split into arg0 'agent' and arg2 'instrument' and all sentences
will have to make the distinction.  Otherwise let's not.
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/resent.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="resent">
<note>
  Frames file for 'resent' based on sentence in financial subcorpus.
  Verbnet class resent 31.2, no mention of other members.  Comparison
  with 'like'.
</note>

<roleset id="resent.01" name="resent" vncls="31.2">
<roles>
  <role descr="resenter" n="0">
		
  <vnrole vncls="31.2" vntheta="Experiencer"/></role>

  <role descr="thing or person resented" n="1">
		
  <vnrole vncls="31.2" vntheta="Cause"/></role>

  <role descr="because-of" n="2"/>
</roles>

<example name="sentential resention">
<text>
    Corporate executives resent that their company's stock has been
    transformed into a nameless piece of a stock-index basket. 
</text>
	<arg n="0">Corporate executives</arg>
	<rel>resent</rel>
	<arg n="1">their company's stock has been transformed into a
	nameless piece of a stock-index basket</arg> 
</example>

<example name="with purpose">
  <text>
    John resents Mary for her perfect grade-point average.
  </text>
  <arg n="0">John</arg>
  <rel>resents</rel>
  <arg n="1">Mary</arg>
  <arg f="for" n="2">her perfect grade-point average</arg>
</example>

<note>
Note that args 1 and 2 can easily be merged: &quot;John resent's Mary's
perfect GPA.&quot;  This is why the reason for resentment deserves to be a
full-fledged Arg rather than an ArgM-PRP.
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/whistle.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="whistle">
<note>
  Frames file for 'whistle' based on sentences in wsj.  Verbnet
  entries 26.7-1, 37.3, 40.2.
</note>

<roleset id="whistle.01" name="make a   whistling noise" vncls="26.7-1 37.3 40.2">
<roles>
  <role descr="maker of noise" n="0"><vnrole vncls="26.7-1" vntheta="Agent"/><vnrole vncls="40.2" vntheta="Agent"/><vnrole vncls="37.3" vntheta="Agent"/></role>
  <role descr="noise itself, tune, utterance" n="1"><vnrole vncls="26.7-1" vntheta="Theme"/><vnrole vncls="40.2" vntheta="Theme"/><vnrole vncls="37.3" vntheta="Topic"/></role>
  <role descr="hearer" n="2"><vnrole vncls="26.7-1" vntheta="Beneficiary"/><vnrole vncls="40.2" vntheta="Recipient"/><vnrole vncls="37.3" vntheta="Recipient"/></role>
</roles>

<example name="whistling Dixie">
<inflection aspect="progressive" form="participle" person="ns" tense="ns" voice="active"/>
<text>
    I don't think anyone left the place *trace* whistling Dixie.''
</text>
        <arg n="0">*trace* -&gt;  anyone</arg>
        <rel>whistling</rel>
        <arg n="1">Dixie</arg>
</example>

<example name="with hearer">
  <inflection aspect="ns" form="full" person="ns" tense="past" voice="active"/>
  <text>
    John whistled at Mary, whereupon she slugged him.
  </text>
  <arg n="0">John</arg>
  <rel>whistled</rel>
  <arg f="at" n="2">Mary</arg>
</example>

<note>
Why, Mary, why are you so violent?
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/stroke.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="stroke">
<note>
  Frames file for 'stroke' based on sentences in financial subcorpus.
  Verbnet entry touch-20, other framed members include sting.
</note>

<roleset id="stroke.01" name="stroke" vncls="20">
<roles>
  <role descr="stroker" n="0">
		
  <vnrole vncls="20" vntheta="Agent"/></role>

  <role descr="thing stroked" n="1">
		
  <vnrole vncls="20" vntheta="Experiencer"/></role>

  <role descr="instrument, if separate from arg0" n="2">
		
  <vnrole vncls="20" vntheta="Instrument"/></role>

</roles>

<example name="transitive">
<text>
    He pampers them; he invites them to fabulous parties; he strokes
    them. 
</text>
        <arg n="0">he</arg>
        <rel>strokes</rel>
        <arg n="1">them</arg>
</example>

<example name="with instrument">
  <text>
    John stroked Mary's back with his foot.
  </text>
  <arg n="0">John</arg>
  <rel>stroked</rel>
  <arg n="1">Mary's back</arg>
  <arg f="with" n="2">his foot</arg>
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/nltk_data/corpora/propbank/frames/smash.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="smash">
<note>
  Frames file for 'smash' based on sentences in wsj.  Verbnet entries
  17.1, 45.1 and 18.4; Framenet entry Cause harm.
</note>

<roleset id="smash.01" name="break violently" vncls="45.1">
<roles>
  <role descr="agent, smasher" n="0"><vnrole vncls="45.1" vntheta="Agent"/></role>
  <role descr="patient, smashed" n="1"><vnrole vncls="45.1" vntheta="Patient"/></role>
</roles>

<example name="both args">
<inflection aspect="progressive" form="participle" person="ns" tense="ns" voice="active"/>
<text>
    Why, when a key witness disappears, does Mancuso trash her
    apartment, [*-3] tearing down drapes, smashing walls? 
</text>
        <arg n="0">[*-3] -&gt;  Mancuso</arg>
        <rel>smashing</rel>
        <arg n="1">walls</arg>
</example>

<note>
</note>

</roleset>

<roleset id="smash.02" name="move violently, so as to break apart" vncls="-">
<roles>
  <role descr="thing in motion" n="1"/>
</roles>

<example name="crunch">
<inflection aspect="ns" form="full" person="ns" tense="past" voice="active"/>
<text>
    The Boeing 727, en route to Honduras from Costa Rica via
    Nicaragua, smashed into the hills outside Tegucigalpa as it
    approached the capital's airport in high winds and low clouds. 
</text>
        <arg n="1">The Boeing 727, en route to Honduras from Costa
        Rica via Nicaragua,</arg> 
        <rel>smashed</rel>
        <arg f="DIR" n="M">into the hills outside Tegucigalpa</arg>
        <arg f="TMP" n="M">as it approached the capital's airport in
        high winds and low clouds</arg> 
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>

=== nltk/nltk/data/corpora/propbank/frames/acquiesce.xml
<!DOCTYPE frameset SYSTEM "frameset.dtd">
<frameset>
<predicate lemma="acquiesce">
<note>
  Frames file for 'acquiesce' based on sentences in wsj.  No Verbnet
  entry. 
</note>

<roleset id="acquiesce.01" name="comply passively" vncls="-">
<roles>
  <role descr="acquiescer, complier" n="0"/>
  <role descr="thing complied to, in, or with" n="1"/>
</roles>

<example name="intransitive">
<inflection aspect="ns" form="full" person="ns" tense="past" voice="active"/>
<text>
    The bank acquiesced.
</text>
        <arg n="0">The bank</arg>
        <rel>acquiesced</rel>
</example>


<example name="transitive">
<inflection aspect="ns" form="infinitive" person="ns" tense="ns" voice="ns"/>
<text>
    A key is whether House Republicans are willing *trace* to
    acquiesce to their Senate colleagues' decision to drop many pet
    provisions. 
</text>
        <arg n="0">*trace* -&gt;  House Republicans</arg>
        <rel>acquiesce</rel>
        <arg f="to" n="1">their Senate colleagues' decision  to drop
        many pet provisions</arg> 
</example>

<note>
</note>

</roleset>
</predicate>
</frameset>
