=== nltk/nltk/data/corpora/nps_chat/postClassPOSTagset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp1 (http://www.altova.com) by Eric Forsyth (Naval Postgraduate School) -->
<!--W3C Schema generated by XMLSpy v2007 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="terminals">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="t" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="t">
		<xs:complexType>
			<xs:attribute name="word" type="xs:string" use="required"/>
			<xs:attribute name="pos" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
						<xs:enumeration value="&apos;&apos;"/>
						<xs:enumeration value="("/>
						<xs:enumeration value=")"/>
						<xs:enumeration value=","/>
						<xs:enumeration value="."/>
						<xs:enumeration value=":"/>
						<xs:enumeration value="BES"/>
						<xs:enumeration value="CC"/>
						<xs:enumeration value="CD"/>
						<xs:enumeration value="DT"/>
						<xs:enumeration value="EX"/>
						<xs:enumeration value="FW"/>
						<xs:enumeration value="GW"/>
						<xs:enumeration value="IN"/>
						<xs:enumeration value="JJ"/>
						<xs:enumeration value="JJR"/>
						<xs:enumeration value="JJS"/>
						<xs:enumeration value="MD"/>
						<xs:enumeration value="NN"/>
						<xs:enumeration value="NNP"/>
						<xs:enumeration value="NNS"/>
						<xs:enumeration value="POS"/>
						<xs:enumeration value="PRP"/>
						<xs:enumeration value="PRP$"/>
						<xs:enumeration value="RB"/>
						<xs:enumeration value="RBR"/>
						<xs:enumeration value="RP"/>
						<xs:enumeration value="SYM"/>
						<xs:enumeration value="TO"/>
						<xs:enumeration value="UH"/>
						<xs:enumeration value="VB"/>
						<xs:enumeration value="VBD"/>
						<xs:enumeration value="VBG"/>
						<xs:enumeration value="VBN"/>
						<xs:enumeration value="VBP"/>
						<xs:enumeration value="VBZ"/>
						<xs:enumeration value="WDT"/>
						<xs:enumeration value="WP"/>
						<xs:enumeration value="WRB"/>
						<xs:enumeration value="^NN"/>
						<xs:enumeration value="``"/>
						<xs:enumeration value="HVS"/>
						<xs:enumeration value="^RB"/>
						<xs:enumeration value="^PRP$"/>
						<xs:enumeration value="^PRP^BES"/>
						<xs:enumeration value="^VBD"/>
						<xs:enumeration value="^VBG"/>
						<xs:enumeration value="^JJ"/>
						<xs:enumeration value="^UH"/>
						<xs:enumeration value="^PRP"/>
						<xs:enumeration value="^VBP"/>
						<xs:enumeration value="^WP^BES"/>
						<xs:enumeration value="^VB"/>
						<xs:enumeration value="^DT"/>
						<xs:enumeration value="^WP"/>
						<xs:enumeration value="^NNS"/>
						<xs:enumeration value="^IN"/>
						<xs:enumeration value="^PRP^VBP"/>
						<xs:enumeration value="^PRP^MD"/>
						<xs:enumeration value="^WRB^BES"/>
						<xs:enumeration value="^VB^PRP"/>
						<xs:enumeration value="^MD^RB"/>
						<xs:enumeration value="^VBP^RB"/>
						<xs:enumeration value="^VBP^RB^PRP"/>
						<xs:enumeration value="^MD"/>
						<xs:enumeration value="^VBP^UH"/>
						<xs:enumeration value="^VBP^PRP"/>
						<xs:enumeration value="^NNP"/>
						<xs:enumeration value="^NN^POS"/>
						<xs:enumeration value="^IN^DT"/>
						<xs:enumeration value="^CC"/>
						<xs:enumeration value="^VBP^DT"/>
						<xs:enumeration value="^TO^VB"/>
						<xs:enumeration value="RBS"/>
						<xs:enumeration value="X"/>
						<xs:enumeration value="^VBZ"/>
						<xs:enumeration value="^DT^NN"/>
						<xs:enumeration value="^VBN"/>
						<xs:enumeration value="NNPS"/>
						<xs:enumeration value="PDT"/>
						<xs:enumeration value="LS"/>
						<xs:enumeration value="#"/>
						<xs:enumeration value="WP$"/>
						<xs:enumeration value="$"/>
						<xs:enumeration value="^RB^PRP"/>
						<xs:enumeration value="^PRP^VBD"/>
						<xs:enumeration value="^UH^NNP"/>
						<xs:enumeration value="^JJ^NN"/>
						<xs:enumeration value="^NN^BES"/>
						<xs:enumeration value="^WRB"/>
						<xs:enumeration value="^RB^VBP"/>
						<xs:enumeration value="^TO"/>
						<xs:enumeration value="^RP"/>
						<xs:enumeration value="^JJS"/>
						<xs:enumeration value="^POS"/>
						<xs:enumeration value="^."/>
						<xs:enumeration value="^JJR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Session">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Posts"/>
			</xs:sequence>
			<xs:attribute name="initialUserCount" type="xs:int" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Posts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Post" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Post">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="terminals"/>
			</xs:sequence>
			<xs:attribute name="user" type="xs:string" use="required"/>
			<xs:attribute name="class" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Accept"/>
						<xs:enumeration value="Bye"/>
						<xs:enumeration value="Clarify"/>
						<xs:enumeration value="Continuer"/>
						<xs:enumeration value="Emotion"/>
						<xs:enumeration value="Emphasis"/>
						<xs:enumeration value="Greet"/>
						<xs:enumeration value="Reject"/>
						<xs:enumeration value="Statement"/>
						<xs:enumeration value="System"/>
						<xs:enumeration value="nAnswer"/>
						<xs:enumeration value="whQuestion"/>
						<xs:enumeration value="yAnswer"/>
						<xs:enumeration value="ynQuestion"/>
						<xs:enumeration value="Other"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nltk/nltk/data/corpora/nps_chat/10-19-20s_706posts.xml
<!-- edited with XMLSpy v2007 sp1 (http://www.altova.com) by Eric Forsyth (Naval Postgraduate School) -->
<Session xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="postClassPOSTagset.xsd">
	<Posts>
		<Post class="Statement" user="10-19-20sUser7">now im left with this gay name<terminals>
				<t pos="RB" word="now"/>
				<t pos="PRP" word="im"/>
				<t pos="VBD" word="left"/>
				<t pos="IN" word="with"/>
				<t pos="DT" word="this"/>
				<t pos="JJ" word="gay"/>
				<t pos="NN" word="name"/>
			</terminals>
		</Post>
		<Post class="Emotion" user="10-19-20sUser7">:P<terminals>
				<t pos="UH" word=":P"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser76">PART<terminals>
				<t pos="VB" word="PART"/>
			</terminals>
		</Post>
		<Post class="Greet" user="10-19-20sUser59">hey everyone  <terminals>
				<t pos="UH" word="hey"/>
				<t pos="NN" word="everyone"/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser115">ah well<terminals>
				<t pos="UH" word="ah"/>
				<t pos="UH" word="well"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser7">NICK :10-19-20sUser7<terminals>
				<t pos="NN" word="NICK"/>
				<t pos=":" word=":"/>
				<t pos="NNP" word="10-19-20sUser7"/>
			</terminals>
		</Post>
		<Post class="Accept" user="10-19-20sUser121">10-19-20sUser7 is a gay name.<terminals>
				<t pos="NNP" word="10-19-20sUser7"/>
				<t pos="VBZ" word="is"/>
				<t pos="DT" word="a"/>
				<t pos="JJ" word="gay"/>
				<t pos="NN" word="name"/>
				<t pos="." word="."/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser84">.ACTION gives 10-19-20sUser121 a golf clap.<terminals>
				<t pos="SYM" word="."/>
				<t pos="NN" word="ACTION"/>
				<t pos="VBZ" word="gives"/>
				<t pos="NNP" word="10-19-20sUser121"/>
				<t pos="DT" word="a"/>
				<t pos="NN" word="golf"/>
				<t pos="NN" word="clap"/>
				<t pos="." word="."/>
			</terminals>
		</Post>
		<Post class="Emotion" user="10-19-20sUser7">:)<terminals>
				<t pos="UH" word=":)"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser123">JOIN<terminals>
				<t pos="VB" word="JOIN"/>
			</terminals>
		</Post>
		<Post class="Greet" user="10-19-20sUser115">hi 10-19-20sUser59<terminals>
				<t pos="UH" word="hi"/>
				<t pos="NNP" word="10-19-20sUser59"/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser21">26/ m/ ky women that are nice please pm me<terminals>
				<t pos="CD" word="26"/>
				<t pos="CC" word="/"/>
				<t pos="NN" word="m"/>
				<t pos="CC" word="/"/>
				<t pos="NNP" word="ky"/>
				<t pos="NNS" word="women"/>
				<t pos="WDT" word="that"/>
				<t pos="VBP" word="are"/>
				<t pos="JJ" word="nice"/>
				<t pos="VB" word="please"/>
				<t pos="VB" word="pm"/>
				<t pos="PRP" word="me"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser124">JOIN<terminals>
				<t pos="VB" word="JOIN"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser77">PART<terminals>
				<t pos="VB" word="PART"/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser115">there ya go 10-19-20sUser7<terminals>
				<t pos="RB" word="there"/>
				<t pos="PRP" word="ya"/>
				<t pos="VBP" word="go"/>
				<t pos="NNP" word="10-19-20sUser7"/>
			</terminals>
		</Post>
		<Post class="Reject" user="10-19-20sUser121">don't golf clap me.<terminals>
				<t pos="VBP" word="do"/>
				<t pos="RB" word="n&apos;t"/>
				<t pos="NN" word="golf"/>
				<t pos="VB" word="clap"/>
				<t pos="PRP" word="me"/>
				<t pos="." word="."/>
			</terminals>
		</Post>
		<Post class="Reject" user="10-19-20sUser7">fuck you 10-19-20sUser121:@<terminals>
				<t pos="VB" word="fuck"/>
				<t pos="PRP" word="you"/>
				<t pos="NNP" word="10-19-20sUser121"/>
				<t pos="UH" word=":@"/>
			</terminals>
		</Post>
		<Post class="whQuestion" user="10-19-20sUser59">whats everyone up to?<terminals>
				<t pos="WP" word="whats"/>
				<t pos="NN" word="everyone"/>
				<t pos="RP" word="up"/>
				<t pos="TO" word="to"/>
				<t pos="." word="?"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser122">PART<terminals>
				<t pos="VB" word="PART"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser117">PART<terminals>
				<t pos="VB" word="PART"/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser121">i'll thunder clap your ass.<terminals>
				<t pos="PRP" word="i"/>
				<t pos="MD" word="&apos;ll"/>
				<t pos="NN" word="thunder"/>
				<t pos="VB" word="clap"/>
				<t pos="PRP$" word="your"/>
				<t pos="NN" word="ass"/>
				<t pos="." word="."/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser91">PART<terminals>
				<t pos="VB" word="PART"/>
			</terminals>
		</Post>
		<Post class="Continuer" user="10-19-20sUser121">and i dont even know what that means.<terminals>
				<t pos="CC" word="and"/>
				<t pos="PRP" word="i"/>
				<t pos="VBP" word="dont"/>
				<t pos="RB" word="even"/>
				<t pos="VB" word="know"/>
				<t pos="WP" word="what"/>
				<t pos="DT" word="that"/>
				<t pos="VBZ" word="means"/>
				<t pos="." word="."/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser84">that sounds painful<terminals>
				<t pos="DT" word="that"/>
				<t pos="VBZ" word="sounds"/>
				<t pos="JJ" word="painful"/>
			</terminals>
		</Post>
		<Post class="ynQuestion" user="10-19-20sUser49">any ladis wanna chat? 29 m<terminals>
				<t pos="DT" word="any"/>
				<t pos="^NNS" word="ladis"/>
				<t pos="VBP" word="wanna"/>
				<t pos="VB" word="chat"/>
				<t pos="." word="?"/>
				<t pos="CD" word="29"/>
				<t pos="NN" word="m"/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser21">26/m<terminals>
				<t pos="CD" word="26"/>
				<t pos="CC" word="/"/>
				<t pos="NN" word="m"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser125">JOIN<terminals>
				<t pos="VB" word="JOIN"/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser115">my cousin drew a messed up pic on my cast<terminals>
				<t pos="PRP$" word="my"/>
				<t pos="NN" word="cousin"/>
				<t pos="VBD" word="drew"/>
				<t pos="DT" word="a"/>
				<t pos="VBD" word="messed"/>
				<t pos="RP" word="up"/>
				<t pos="NN" word="pic"/>
				<t pos="IN" word="on"/>
				<t pos="PRP$" word="my"/>
				<t pos="NN" word="cast"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser114">PART<terminals>
				<t pos="VB" word="PART"/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser23">24/m<terminals>
				<t pos="CD" word="24"/>
				<t pos="CC" word="/"/>
				<t pos="NN" word="m"/>
			</terminals>
		</Post>
		<Post class="Emotion" user="10-19-20sUser121">boo.<terminals>
				<t pos="UH" word="boo"/>
				<t pos="." word="."/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser21">26/m and sexy<terminals>
				<t pos="CD" word="26"/>
				<t pos="CC" word="/"/>
				<t pos="NN" word="m"/>
				<t pos="CC" word="and"/>
				<t pos="JJ" word="sexy"/>
			</terminals>
		</Post>
		<Post class="Emotion" user="10-19-20sUser7">lol 10-19-20sUser115<terminals>
				<t pos="UH" word="lol"/>
				<t pos="NNP" word="10-19-20sUser115"/>
			</terminals>
		</Post>
		<Post class="Emotion" user="10-19-20sUser121">boo.<terminals>
				<t pos="UH" word="boo"/>
				<t pos="." word="."/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser126">JOIN<terminals>
				<t pos="VB" word="JOIN"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser19">PART<terminals>
				<t pos="VB" word="PART"/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser115">he drew a girl with legs spread<terminals>
				<t pos="PRP" word="he"/>
				<t pos="VBD" word="drew"/>
				<t pos="DT" word="a"/>
				<t pos="NN" word="girl"/>
				<t pos="IN" word="with"/>
				<t pos="NNS" word="legs"/>
				<t pos="VB" word="spread"/>
			</terminals>
		</Post>
		<Post class="Emotion" user="10-19-20sUser121">boo.<terminals>
				<t pos="UH" word="boo"/>
				<t pos="." word="."/>
			</terminals>
		</Post>
		<Post class="Statement" user="10-19-20sUser7">hope he didnt draw a penis<terminals>
				<t pos="VBP" word="hope"/>
				<t pos="PRP" word="he"/>
				<t pos="VBD" word="didnt"/>
				<t pos="VB" word="draw"/>
				<t pos="DT" word="a"/>
				<t pos="NN" word="penis"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser67">PART<terminals>
				<t pos="VB" word="PART"/>
			</terminals>
		</Post>
		<Post class="Emotion" user="10-19-20sUser7">ewwwww lol<terminals>
				<t pos="UH" word="ewwwww"/>
				<t pos="UH" word="lol"/>
			</terminals>
		</Post>
		<Post class="Continuer" user="10-19-20sUser115">&amp; a head between her legs<terminals>
				<t pos="CC" word="&amp;"/>
				<t pos="DT" word="a"/>
				<t pos="NN" word="head"/>
				<t pos="IN" word="between"/>
				<t pos="PRP$" word="her"/>
				<t pos="NNS" word="legs"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser127">JOIN<terminals>
				<t pos="VB" word="JOIN"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser128">JOIN<terminals>
				<t pos="VB" word="JOIN"/>
			</terminals>
		</Post>
		<Post class="Accept" user="10-19-20sUser121">sounds good to me.<terminals>
				<t pos="VBZ" word="sounds"/>
				<t pos="JJ" word="good"/>
				<t pos="TO" word="to"/>
				<t pos="PRP" word="me"/>
				<t pos="." word="."/>
			</terminals>
		</Post>
		<Post class="ynQuestion" user="10-19-20sUser7">r u serious<terminals>
				<t pos="VBP" word="r"/>
				<t pos="PRP" word="u"/>
				<t pos="JJ" word="serious"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser129">JOIN<terminals>
				<t pos="VB" word="JOIN"/>
			</terminals>
		</Post>
		<Post class="System" user="10-19-20sUser65">PART<terminals>
				<t pos="VB" word="PART"/>
			</terminals>
		</Post>
