=== nltk/nltk/data/corpora/verbnet/vn_class-3.dtd
<!ELEMENT VNCLASS (MEMBERS,THEMROLES,FRAMES,SUBCLASSES)>
<!ATTLIST VNCLASS ID ID #REQUIRED
                  xmlns:xsi CDATA #IMPLIED
                  xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

<!ELEMENT VNSUBCLASS (MEMBERS,THEMROLES,FRAMES,SUBCLASSES)>
<!ATTLIST VNSUBCLASS ID ID #REQUIRED>

<!ELEMENT MEMBERS (MEMBER*)>
<!ELEMENT THEMROLES (THEMROLE*)>
<!ELEMENT SELRESTRS (SELRESTR|SELRESTRS)*>
<!ATTLIST SELRESTRS logic (and|or) #IMPLIED>

<!ELEMENT FRAMES (FRAME*)>
<!ELEMENT SUBCLASSES (VNSUBCLASS*)>

<!ELEMENT FRAME (DESCRIPTION,EXAMPLES,SYNTAX,SEMANTICS)>
<!ELEMENT EXAMPLES (EXAMPLE*)>

<!ELEMENT MEMBER EMPTY>
<!ATTLIST MEMBER name CDATA #REQUIRED
                 wn CDATA #REQUIRED>

<!ELEMENT THEMROLE (SELRESTRS)>
<!ATTLIST THEMROLE type CDATA #REQUIRED>

<!ELEMENT SELRESTR EMPTY>
<!ATTLIST SELRESTR Value CDATA #REQUIRED
                   type  CDATA #REQUIRED>

<!ELEMENT DESCRIPTION EMPTY>
<!ATTLIST DESCRIPTION primary CDATA #REQUIRED
                      secondary CDATA #IMPLIED
                      descriptionNumber CDATA #REQUIRED 
                      xtag CDATA #REQUIRED> 

<!ELEMENT EXAMPLE (#PCDATA)>
<!ELEMENT SYNTAX (NP|VERB|ADJ|ADV|PREP|LEX)+>
<!ELEMENT SEMANTICS (PRED+)>

<!ELEMENT NP (SYNRESTRS|SELRESTRS)>
<!ATTLIST NP value CDATA #REQUIRED>

<!ELEMENT SYNRESTRS (SYNRESTR*)>
<!ATTLIST SYNRESTRS logic (and|or) #IMPLIED>

<!ELEMENT SYNRESTR EMPTY>
<!ATTLIST SYNRESTR Value CDATA #REQUIRED
                   type  CDATA #REQUIRED>

<!ELEMENT VERB EMPTY>
<!ELEMENT ADJ EMPTY>
<!ELEMENT ADV EMPTY>

<!ELEMENT PREP (SELRESTRS)>
<!ATTLIST PREP value CDATA #IMPLIED>

<!ELEMENT LEX EMPTY>
<!ATTLIST LEX value CDATA #REQUIRED>

<!ELEMENT PRED (ARGS)>
<!ATTLIST PRED bool CDATA #IMPLIED
               value CDATA #REQUIRED>

<!ELEMENT ARGS (ARG+)>
<!ELEMENT ARG EMPTY>
<!ATTLIST ARG type (Event|ThemRole|VerbSpecific|Constant) #REQUIRED
              value CDATA #REQUIRED>

=== nltk/nltk/data/corpora/verbnet/hurt-40_8_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="hurt-40.8.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
    <MEMBERS/>
    <THEMROLES>
        <THEMROLE type="Experiencer">
            <SELRESTRS>
                <SELRESTR Value="+" type="animate"/>
            </SELRESTRS>
        </THEMROLE>
        <THEMROLE type="Patient">
            <SELRESTRS logic="or">
                <SELRESTR Value="+" type="body_part"/>
                <SELRESTR Value="+" type="refl"/>
            </SELRESTRS>
        </THEMROLE>
    </THEMROLES>
    <FRAMES/>
    <SUBCLASSES>
        <VNSUBCLASS ID="hurt-40.8.3-1">
            <MEMBERS>
                <MEMBER name="stub" wn="stub%2:29:00"/>
            </MEMBERS>
            <THEMROLES>
                <THEMROLE type="Patient">
                    <SELRESTRS>
                        <SELRESTR Value="+" type="body_part"/>
                    </SELRESTRS>
                </THEMROLE>
            </THEMROLES>
            <FRAMES>
                <FRAME>
                    <DESCRIPTION descriptionNumber="7.6" primary="Unintentional Interpretation of Object" secondary="Body_part Object" xtag=""/>
                    <EXAMPLES>
                        <EXAMPLE>Tessa hurt/sprained her ankle.</EXAMPLE>
                    </EXAMPLES>
                    <SYNTAX>
                        <NP value="Experiencer">
                            <SYNRESTRS/>
                        </NP>
                        <VERB/>
                        <NP value="Patient">
                            <SYNRESTRS/>
                        </NP>
                    </SYNTAX>
                    <SEMANTICS>
                        <PRED value="harmed">
                            <ARGS>
                                <ARG type="Event" value="during(E)"/>
                                <ARG type="ThemRole" value="Patient"/>
                            </ARGS>
                        </PRED>
                        <PRED value="experience">
                            <ARGS>
                                <ARG type="Event" value="E"/>
                                <ARG type="ThemRole" value="Experiencer"/>
                            </ARGS>
                        </PRED>
                    </SEMANTICS>
                </FRAME>
            </FRAMES>
            <SUBCLASSES>
                <VNSUBCLASS ID="hurt-40.8.3-1-1">
                    <MEMBERS>
                        <!--verb adds manner predicate for how the Patient is hurt-->
                        <MEMBER name="break" wn="break%2:35:13 break%2:35:09 break%2:30:15 break%2:29:04"/>
                        <MEMBER name="chip" wn="chip%2:35:00"/>
                        <MEMBER name="fracture" wn="fracture%2:29:02 fracture%2:29:01 fracture%2:29:00"/>
                        <MEMBER name="pull" wn="pull%2:29:00"/>
                        <MEMBER name="rupture" wn="rupture%2:35:00"/>
                        <MEMBER name="split" wn="split%2:35:00"/>
                        <MEMBER name="sprain" wn="sprain%2:29:00"/>
                        <MEMBER name="turn" wn="turn%2:29:00"/>
                        <MEMBER name="twist" wn="twist%2:29:00"/>
                    </MEMBERS>
                    <THEMROLES/>
                    <FRAMES>
                        <FRAME>
                            <DESCRIPTION descriptionNumber="0.1" primary="Intransitive" secondary="" xtag="0.1"/>
                            <EXAMPLES>
                                <EXAMPLE>My ankle twisted.</EXAMPLE>
                            </EXAMPLES>
                            <SYNTAX>
                                <NP value="Patient">
                                    <SYNRESTRS/>
                                </NP>
                                <VERB/>
                            </SYNTAX>
                            <SEMANTICS>
                                <PRED value="harmed">
                                    <ARGS>
                                        <ARG type="Event" value="during(E)"/>
                                        <ARG type="ThemRole" value="Patient"/>
                                    </ARGS>
                                </PRED>
                                <PRED value="experience">
                                    <ARGS>
                                        <ARG type="Event" value="E"/>
                                        <ARG type="ThemRole" value="?Experiencer"/>
                                    </ARGS>
                                </PRED>
                            </SEMANTICS>
                        </FRAME>
                    </FRAMES>
                    <SUBCLASSES/>
                </VNSUBCLASS>
            </SUBCLASSES>
        </VNSUBCLASS>
        <VNSUBCLASS ID="hurt-40.8.3-2">
            <MEMBERS>
                <!--verb adds manner predicate for how the Patient is hurt-->
                <MEMBER name="bark" wn=""/>
                <MEMBER name="bite" wn="bite%2:35:00"/>
                <MEMBER name="bruise" wn="bruise%2:35:00"/>
                <MEMBER name="bump" wn="bump%2:35:00"/>
                <MEMBER name="burn" wn="burn%2:30:02 burn%2:39:00"/>
                <MEMBER name="cut" wn="cut%2:35:14"/>
                <MEMBER name="hurt" wn="hurt%2:29:01"/>
                <MEMBER name="injure" wn="injure%2:29:00"/>
                <MEMBER name="nick" wn="nick%2:35:01"/>
                <MEMBER name="prick" wn="prick%2:35:00 prick%2:35:03"/>
                <MEMBER name="scald" wn="scald%2:30:00"/>
                <MEMBER name="scratch" wn="scratch%2:35:00 ?scratch%2:39:00"/>
                <MEMBER name="skin" wn="skin%2:35:02"/>
                <MEMBER name="strain" wn="strain%2:34:00"/>
            </MEMBERS>
            <THEMROLES/>
            <FRAMES>
                <FRAME>
                    <DESCRIPTION descriptionNumber="7.6" primary="Unintentional Interpretation of Object" secondary="Body_part Object" xtag=""/>
                    <EXAMPLES>
                        <EXAMPLE>Tessa hurt/sprained her ankle.</EXAMPLE>
                    </EXAMPLES>
                    <SYNTAX>
                        <NP value="Experiencer">
                            <SYNRESTRS/>
                        </NP>
                        <VERB/>
                        <NP value="Patient">
                            <SYNRESTRS/>
                        </NP>
                    </SYNTAX>
                    <SEMANTICS>
                        <PRED value="harmed">
                            <ARGS>
                                <ARG type="Event" value="during(E)"/>
                                <ARG type="ThemRole" value="Patient"/>
                            </ARGS>
                        </PRED>
                        <PRED value="experience">
                            <ARGS>
                                <ARG type="Event" value="E"/>
                                <ARG type="ThemRole" value="Experiencer"/>
                            </ARGS>
                        </PRED>
                    </SEMANTICS>
                </FRAME>
                <FRAME>
                    <DESCRIPTION descriptionNumber="7.6" primary="Unintentional Interpretation of Object" secondary="Reflexive Object" xtag=""/>
                    <EXAMPLES>
                        <EXAMPLE>Tessa hurt herself.</EXAMPLE>
                    </EXAMPLES>
                    <SYNTAX>
                        <NP value="Experiencer">
                            <SYNRESTRS/>
                        </NP>
                        <VERB/>
                        <NP value="Patient">
                            <SYNRESTRS/>
                        </NP>
                    </SYNTAX>
                    <SEMANTICS>
                        <PRED value="harmed">
                            <ARGS>
                                <ARG type="Event" value="during(E)"/>
                                <ARG type="ThemRole" value="Patient"/>
                            </ARGS>
                        </PRED>
                        <PRED value="experience">
                            <ARGS>
                                <ARG type="Event" value="E"/>
                                <ARG type="ThemRole" value="Experiencer"/>
                            </ARGS>
                        </PRED>
                    </SEMANTICS>
                </FRAME>
            </FRAMES>
            <SUBCLASSES/>
        </VNSUBCLASS>
    </SUBCLASSES>
</VNCLASS>

=== nltk/nltk/data/corpora/verbnet/poison-42.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="poison-42.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
    <MEMBERS>
        <!--Each member adds a manner predicate-->
        <MEMBER name="asphyxiate" wn="asphyxiate%2:35:00"/>
        <MEMBER name="crucify" wn="crucify%2:41:00"/>
        <MEMBER name="drown" wn="drown%2:30:01"/>
        <MEMBER name="electrocute" wn="electrocute%2:41:00"/>
        <MEMBER name="garrotte" wn="garrotte%2:35:00"/>
        <MEMBER name="hang" wn="hang%2:41:00"/>
        <MEMBER name="knife" wn="knife%2:35:00"/>
        <MEMBER name="poison" wn="poison%2:35:00"/>
        <MEMBER name="shoot" wn="shoot%2:41:00"/>
        <MEMBER name="smother" wn="smother%2:35:00"/>
        <MEMBER name="stab" wn="stab%2:35:02"/>
        <MEMBER name="strangle" wn="strangle%2:35:00"/>
        <MEMBER name="suffocate" wn="suffocate%2:35:00"/>
    </MEMBERS>
    <THEMROLES>
        <THEMROLE type="Agent">
            <SELRESTRS>
                <SELRESTR Value="+" type="animate"/>
            </SELRESTRS>
        </THEMROLE>
        <THEMROLE type="Patient">
            <SELRESTRS>
                <SELRESTR Value="+" type="animate"/>
            </SELRESTRS>
        </THEMROLE>
        <THEMROLE type="Instrument">
            <SELRESTRS/>
        </THEMROLE>
    </THEMROLES>
    <FRAMES>
        <FRAME>
            <DESCRIPTION descriptionNumber="0.2" primary="Basic Transitive" secondary="" xtag="0.2"/>
            <EXAMPLES>
                <EXAMPLE>The witch poisoned Snow White.</EXAMPLE>
            </EXAMPLES>
            <SYNTAX>
                <NP value="Agent">
                    <SYNRESTRS/>
                </NP>
                <VERB/>
                <NP value="Patient">
                    <SYNRESTRS/>
                </NP>
            </SYNTAX>
            <SEMANTICS>
                <PRED value="cause">
                    <ARGS>
                        <ARG type="ThemRole" value="Agent"/>
                        <ARG type="Event" value="E"/>
                    </ARGS>
                </PRED>
                <PRED value="harmed">
                    <ARGS>
                        <ARG type="Event" value="during(E)"/>
                        <ARG type="ThemRole" value="Patient"/>
                    </ARGS>
                </PRED>
            </SEMANTICS>
        </FRAME>
        <FRAME>
            <DESCRIPTION descriptionNumber="0.4" primary="NP-ADJP" secondary="Resultative" xtag=""/>
            <EXAMPLES>
                <EXAMPLE>The Boston Strangler strangled his victims dead.</EXAMPLE>
            </EXAMPLES>
            <SYNTAX>
                <NP value="Agent">
                    <SYNRESTRS/>
                </NP>
                <VERB/>
                <NP value="Patient">
                    <SYNRESTRS/>
                </NP>
                <ADJ/>
            </SYNTAX>
            <SEMANTICS>
                <PRED value="cause">
                    <ARGS>
                        <ARG type="ThemRole" value="Agent"/>
                        <ARG type="Event" value="E"/>
                    </ARGS>
                </PRED>
                <PRED value="harmed">
                    <ARGS>
                        <ARG type="Event" value="during(E)"/>
                        <ARG type="ThemRole" value="Patient"/>
                    </ARGS>
                </PRED>
                <PRED value="Pred">
                    <ARGS>
                        <ARG type="Event" value="result(E)"/>
                        <ARG type="ThemRole" value="Patient"/>
                    </ARGS>
                </PRED>
            </SEMANTICS>
            <!--most verbs-->
        </FRAME>
        <FRAME>
            <DESCRIPTION descriptionNumber="0.4" primary="NP-PP" secondary="Result-PP" xtag=""/>
            <EXAMPLES>
                <EXAMPLE>The Boston Strangler strangled his victims to death.</EXAMPLE>
            </EXAMPLES>
            <SYNTAX>
                <NP value="Agent">
                    <SYNRESTRS/>
                </NP>
                <VERB/>
                <NP value="Patient">
                    <SYNRESTRS/>
                </NP>
                <PREP value="to into">
                    <SELRESTRS/>
                </PREP>
                <NP value="Oblique">
                    <SELRESTRS>
                        <SELRESTR Value="+" type="state"/>
                    </SELRESTRS>
                </NP>
            </SYNTAX>
            <SEMANTICS>
                <PRED value="cause">
                    <ARGS>
                        <ARG type="ThemRole" value="Agent"/>
                        <ARG type="Event" value="E"/>
                    </ARGS>
                </PRED>
                <PRED value="harmed">
                    <ARGS>
                        <ARG type="Event" value="during(E)"/>
                        <ARG type="ThemRole" value="Patient"/>
                    </ARGS>
                </PRED>
                <PRED value="Pred">
                    <ARGS>
                        <ARG type="Event" value="result(E)"/>
                        <ARG type="ThemRole" value="Patient"/>
                    </ARGS>
                </PRED>
            </SEMANTICS>
            <!--most verbs-->
        </FRAME>
        <FRAME>
            <DESCRIPTION descriptionNumber="" primary="NP-PP" secondary="Instrument-PP" xtag=""/>
            <EXAMPLES>
                <EXAMPLE>The queen poisoned Snow White with an apple.</EXAMPLE>
            </EXAMPLES>
            <SYNTAX>
                <NP value="Agent">
                    <SYNRESTRS/>
                </NP>
                <VERB/>
                <NP value="Patient">
                    <SYNRESTRS/>
                </NP>
                <PREP value="with">
                    <SELRESTRS/>
                </PREP>
                <NP value="Instrument">
                    <SYNRESTRS/>
                </NP>
            </SYNTAX>
            <SEMANTICS>
                <PRED value="cause">
                    <ARGS>
                        <ARG type="ThemRole" value="Agent"/>
                        <ARG type="Event" value="E"/>
                    </ARGS>
                </PRED>
                <PRED value="harmed">
                    <ARGS>
                        <ARG type="Event" value="during(E)"/>
                        <ARG type="ThemRole" value="Patient"/>
                    </ARGS>
                </PRED>
            </SEMANTICS>
        </FRAME>
    </FRAMES>
    <SUBCLASSES/>
</VNCLASS>

=== nltk/nltk/data/corpora/verbnet/settle-89.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="settle-89" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
    <MEMBERS>
        <MEMBER name="settle" wn=""/>
        <MEMBER name="concur" wn=""/>
        <MEMBER name="contract" wn=""/>
        <MEMBER name="harmonize" wn=""/>
        <MEMBER name="bargain" wn=""/>
        <MEMBER name="consent" wn=""/>
        <MEMBER name="cohere" wn=""/>
        <MEMBER name="jibe" wn=""/>
        <MEMBER name="square" wn=""/>
    </MEMBERS>
    <THEMROLES>
        <THEMROLE type="Actor">
            <SELRESTRS logic="or">
                <SELRESTR Value="+" type="animate"/>
                <SELRESTR Value="+" type="organization"/>
            </SELRESTRS>
        </THEMROLE>
        <THEMROLE type="Proposition">
            <SELRESTRS/>
        </THEMROLE>
    </THEMROLES>
    <FRAMES>
        <FRAME>
            <DESCRIPTION descriptionNumber="8.1" primary="Basic Intransitive" secondary="" xtag="0.2"/>
            <EXAMPLES>
                <EXAMPLE>Eventually, they settled.</EXAMPLE>
            </EXAMPLES>
            <SYNTAX>
                <NP value="Actor">
                    <SYNRESTRS>
                        <SYNRESTR Value="+" type="plural"/>
                    </SYNRESTRS>
                </NP>
                <VERB/>
            </SYNTAX>
            <SEMANTICS>
                <PRED value="agree">
                    <ARGS>
                        <ARG type="Event" value="result(E)"/>
                        <ARG type="ThemRole" value="Actor"/>
                        <ARG type="ThemRole" value="?Proposition"/>
                    </ARGS>
                </PRED>
            </SEMANTICS>
        </FRAME>
        <FRAME>
            <DESCRIPTION descriptionNumber="8.1" primary="P-WHAT-TO-INF" secondary="on-PP" xtag="0.2"/>
            <EXAMPLES>
                <EXAMPLE>They settled on what to do.</EXAMPLE>
            </EXAMPLES>
            <SYNTAX>
                <NP value="Actor">
                    <SYNRESTRS>
                        <SYNRESTR Value="+" type="plural"/>
                    </SYNRESTRS>
                </NP>
                <VERB/>
                <PREP value="on">
                    <SELRESTRS/>
                </PREP>
                <NP value="Proposition">
                    <SYNRESTRS>
                        <SYNRESTR Value="+" type="what_inf"/>
                    </SYNRESTRS>
                </NP>
            </SYNTAX>
            <SEMANTICS>
                <PRED value="agree">
                    <ARGS>
                        <ARG type="Event" value="result(E)"/>
                        <ARG type="ThemRole" value="Actor"/>
                        <ARG type="ThemRole" value="Proposition"/>
                    </ARGS>
                </PRED>
            </SEMANTICS>
        </FRAME>
    </FRAMES>
    <SUBCLASSES/>
</VNCLASS>

=== nltk/nltk/data/corpora/verbnet/dub-29.3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VNCLASS SYSTEM "vn_class-3.dtd">
<VNCLASS ID="dub-29.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vn_schema-3.xsd">
    <MEMBERS>
        <MEMBER name="call" wn="call%2:32:02 call%2:32:00 call%2:41:14"/>
        <MEMBER name="decree" wn="decree%2:31:00"/>
        <MEMBER name="dub" wn="dub%2:32:00"/>
        <MEMBER name="make" wn="make%2:30:00 make%2:41:03"/>
        <MEMBER name="pronounce" wn="pronounce%2:32:01 pronounce%2:32:00"/>
        <MEMBER name="rule" wn="rule%2:31:00"/>
        <MEMBER name="stamp" wn="stamp%2:39:00"/>
        <MEMBER name="term" wn="term%2:32:00"/>
        <MEMBER name="vote" wn="vote%2:41:12"/>
    </MEMBERS>
    <THEMROLES>
        <THEMROLE type="Agent">
            <SELRESTRS logic="or">
                <SELRESTR Value="+" type="animate"/>
                <SELRESTR Value="+" type="organization"/>
            </SELRESTRS>
        </THEMROLE>
        <THEMROLE type="Theme">
            <SELRESTRS logic="or">
                <SELRESTR Value="+" type="concrete"/>
                <SELRESTR Value="+" type="organization"/>
            </SELRESTRS>
        </THEMROLE>
        <THEMROLE type="Predicate">
            <SELRESTRS/>
        </THEMROLE>
    </THEMROLES>
    <FRAMES>
        <FRAME>
            <DESCRIPTION descriptionNumber="0.2" primary="NP-NP" secondary="" xtag=""/>
            <EXAMPLES>
                <EXAMPLE>The captain named the ship Seafarer.</EXAMPLE>
            </EXAMPLES>
            <SYNTAX>
                <NP value="Agent">
                    <SYNRESTRS/>
                </NP>
                <VERB/>
                <NP value="Theme">
                    <SYNRESTRS/>
                </NP>
                <NP value="Predicate">
                    <SYNRESTRS/>
                </NP>
            </SYNTAX>
            <SEMANTICS>
                <PRED value="designated">
                    <ARGS>
                        <ARG type="Event" value="result(E)"/>
                        <ARG type="ThemRole" value="Theme"/>
                        <ARG type="ThemRole" value="Predicate"/>
                    </ARGS>
                </PRED>
                <PRED value="cause">
                    <ARGS>
                        <ARG type="ThemRole" value="Agent"/>
                        <ARG type="Event" value="E"/>
                    </ARGS>
                </PRED>
            </SEMANTICS>
        </FRAME>
        <FRAME>
            <DESCRIPTION descriptionNumber="" primary="Basic Transitive" secondary="" xtag=""/>
            <EXAMPLES>
                <EXAMPLE>The captain baptized the ship.</EXAMPLE>
            </EXAMPLES>
            <SYNTAX>
                <NP value="Agent">
                    <SYNRESTRS/>
                </NP>
                <VERB/>
                <NP value="Theme">
                    <SYNRESTRS/>
                </NP>
            </SYNTAX>
            <SEMANTICS>
                <PRED value="cause">
                    <ARGS>
                        <ARG type="ThemRole" value="Agent"/>
                        <ARG type="Event" value="E"/>
                    </ARGS>
                </PRED>
                <PRED value="designated">
                    <ARGS>
                        <ARG type="Event" value="result(E)"/>
                        <ARG type="ThemRole" value="Theme"/>
                        <ARG type="ThemRole" value="?Predicate"/>
                    </ARGS>
                </PRED>
            </SEMANTICS>
        </FRAME>
    </FRAMES>
    <SUBCLASSES>
        <VNSUBCLASS ID="dub-29.3-1">
            <MEMBERS>
                <MEMBER name="anoint" wn="anoint%2:29:00"/>
                <MEMBER name="baptize" wn="baptize%2:32:00"/>
                <MEMBER name="brand" wn="brand%2:32:00"/>
                <MEMBER name="christen" wn="christen%2:32:00"/>
                <MEMBER name="consecrate" wn="consecrate%2:41:00 consecrate%2:32:01 consecrate%2:32:00"/>
                <MEMBER name="crown" wn="crown%2:41:00"/>
                <MEMBER name="label" wn="label%2:32:01"/>
                <MEMBER name="name" wn="name%2:32:03 name%2:41:01 name%2:41:00"/>
                <MEMBER name="nickname" wn="nickname%2:32:00"/>
                <MEMBER name="style" wn="style%2:32:00"/>
            </MEMBERS>
            <THEMROLES/>
            <FRAMES>
                <FRAME>
                    <DESCRIPTION descriptionNumber="" primary="NP-PP" secondary="after-PP" xtag=""/>
                    <EXAMPLES>
                        <EXAMPLE>They named it after Ira Cohen.</EXAMPLE>
                    </EXAMPLES>
                    <SYNTAX>
                        <NP value="Agent">
                            <SYNRESTRS/>
                        </NP>
                        <VERB/>
                        <NP value="Theme">
                            <SYNRESTRS/>
                        </NP>
                        <PREP value="after">
                            <SELRESTRS/>
                        </PREP>
                        <NP value="Predicate">
                            <SYNRESTRS/>
                        </NP>
                    </SYNTAX>
                    <SEMANTICS>
                        <PRED value="designated">
                            <ARGS>
                                <ARG type="Event" value="result(E)"/>
                                <ARG type="ThemRole" value="Theme"/>
                                <ARG type="ThemRole" value="Predicate"/>
                            </ARGS>
                        </PRED>
                        <PRED value="cause">
                            <ARGS>
                                <ARG type="ThemRole" value="Agent"/>
                                <ARG type="Event" value="E"/>
                            </ARGS>
                        </PRED>
                    </SEMANTICS>
                </FRAME>
                <FRAME>
                    <DESCRIPTION descriptionNumber="" primary="NP-PP" secondary="for-PP" xtag=""/>
                    <EXAMPLES>
                        <EXAMPLE>They named it for Charlie Brown.</EXAMPLE>
                    </EXAMPLES>
                    <SYNTAX>
                        <NP value="Agent">
                            <SYNRESTRS/>
                        </NP>
                        <VERB/>
                        <NP value="Theme">
                            <SYNRESTRS/>
                        </NP>
                        <PREP value="for">
                            <SELRESTRS/>
                        </PREP>
                        <NP value="Predicate">
                            <SYNRESTRS/>
                        </NP>
                    </SYNTAX>
                    <SEMANTICS>
                        <PRED value="designated">
                            <ARGS>
                                <ARG type="Event" value="result(E)"/>
                                <ARG type="ThemRole" value="Theme"/>
                                <ARG type="ThemRole" value="Predicate"/>
                            </ARGS>
                        </PRED>
                        <PRED value="cause">
                            <ARGS>
                                <ARG type="ThemRole" value="Agent"/>
                                <ARG type="Event" value="E"/>
                            </ARGS>
                        </PRED>
                    </SEMANTICS>
                </FRAME>
            </FRAMES>
            <SUBCLASSES/>
        </VNSUBCLASS>
    </SUBCLASSES>
</VNCLASS>
